INSERT INTO pv_sectorProfesion (nombre) VALUES
('Ingeniería'),('Derecho'),
('Finanzas'),('Construcción'),
('Agricultura'),('Gastronomía'),
('Medios de Comunicación'),('Diseño Gráfico'),
('Recursos Humanos'),('Logística'),
('Biotecnología'),('Energías Renovables'),
('Turismo'),('Moda'),
('Consultoría'),('Seguros'),
('Arquitectura'),('Farmacéutica'),
('Automotriz'),('Aeroespacial'),
('Videojuegos'),('Inteligencia Artificial'),
('Ciberseguridad'),('Economía'),
('Psicología'),('Veterinaria'),
('Medio Ambiente'),('Deportes'),
('Música'),('Cine y Televisión'),
('Relaciones Públicas'),('Comercio Electrónico'),
('Blockchain'),('Nanotecnología'),
('Robótica');