USE VotoPV01
GO

INSERT INTO pv_afiliaciones (nombre)
VALUES
('Universidad de Costa Rica'),
('Instituto Tecnológico de Costa Rica'),
('Universidad Nacional de Costa Rica'),
('Universidad Estatal a Distancia'),
('Universidad Técnica Nacional'),
('Universidad Latina de Costa Rica'),
('Universidad Hispanoamericana'),
('Universidad Fidélitas'),
('Universidad Internacional de las Américas'),
('Universidad Autónoma de Centro América'),
('Universidad San Marcos'),
('INCAE Business School'),
('Universidad de Ciencias Médicas'),
('Universidad EARTH'),
('Universidad para la Paz'),
('Universidad Creativa'),
('Universidad Juan Pablo II'),
('Universidad Adventista de Centroamérica'),
('Universidad Federada San Judas Tadeo'),
('Facultad Autónoma de Ciencias Odontológicas'),
('Universidad Federada de Costa Rica'),
('Universidad Libre de Costa Rica'),
('Universidad Santa Lucía'),
('Universidad La Salle'),
('Universidad Politécnica Internacional'),
('Lead University'),
('Universidad Braulio Carrillo'),
('Universidad Castro Carazo'),
('Universidad Central de Costa Rica'),
('Universidad de San José'),
('CENFOTEC'),
('Universidad de Iberoamérica'),
('Escuela Libre de Derecho'),
('Colegio Universitario de Cartago'),
('Colegio Universitario Limón'),
('Universidad Veritas'),
('Florida Ice and Farm Company'),
('Cooperativa de Productores de Leche Dos Pinos'),
('BAC Credomatic'),
('Grupo Purdy'),
('Coca-Cola FEMSA'),
('Intel Costa Rica'),
('Auto Mercado'),
('Procter & Gamble'),
('Kimberly Clark'),
('Walmart Centroamérica'),
('Bridgestone Firestone Costa Rica'),
('Microsoft'),
('Banco Nacional de Costa Rica'),
('DHL'),
('Apple'),
('Grupo ICE'),
('Amazon'),
('Hewlett-Packard -- HP'),
('Ad Astra Rocket Company'),
('Café Britt'),
('Grupo El Ángel'),
('Durman Esquivel'),
('Grupo Monge'),
('Bayer'),
('Hospital Clínica Bíblica'),
('Tiendas Universal'),
('Teletica (Televisora de Costa Rica)'),
('Marriott International'),
('IBM'),
('Cisco Systems'),
('Grupo INS'),
('Banco de Costa Rica'),
('Cargill'),
('Pfizer'),
('Grupo Q'),
('Grupo Danissa - Nissan'),
('Grupo Bimbo'),
('Farmacias La Bomba'),
('Scotiabank'),
('Samsung Electronics'),
('Davivienda Costa Rica'),
('Hospital CIMA San José'),
('SC Johnson'),
('Holcim'),
('Grupo Irex'),
('McDonalds'),
('Avianca'),
('Grupo Sur'),
('Nestlé'),
('Unilever'),
('Banco Popular'),
('Abbott Laboratories'),
('Grupo Nación'),
('El Pelón de la Bajura'),
('Sanofi'),
('Alimentos Prosalud'),
('Roche'),
('Florex'),
('Liberty Latin America'),
('AstraZeneca'),
('3M Costa Rica'),
('Novartis'),
('Deloitte Costa Rica'),
('GSK'),
('Del Monte Fresh Produce'),
('Grupo Promerica'),
('Baxter'),
('Sykes Enterprises'),
('Cemex'),
('Claro Costa Rica'),
('Constructora Meco'),
('Compañía de Galletas Pozuelo'),
('Cuestamoras'),
('SCA Corporate'),
('Mondelēz International'),
('Smith & Nephew'),
('Boston Scientific'),
('Garnier & Garnier Desarrollos Inmobiliarios'),
('Constructora Volio & Trejos'),
('Schneider Electric'),
('Globalvia Ruta 27'),
('Constructora Van der Laat y Jiménez'),
('Palacio de Modas'),
('Kirebe'),
('Grupo Poma'),
('Grupo Unicomer'),
('Western Union'),
('Mesoamérica'),
('DEMASA'),
('PwC'),
('PriceSmart'),
('Banco Lafise'),
('Tigo Costa Rica'),
('Starbucks Costa Rica'),
('Coope Ande'),
('Coopealianza'),
('Coopelesca'),
('Grupo Mutual'),
('PROCOMER'),
('EPA'),
('Almacenes El Rey'),
('Tiendas Pequeño Mundo'),
('Telecable'),
('Colgate-Palmolive'),
('Grupo Numar'),
('Mayca Food Service'),
('Gutis Farmacéutica'),
('Nacascolo Holdings'),
('Metalco'),
('Bacardi');


INSERT INTO pv_afiliacionesUsuario(usarioID, afiliacionID)
SELECT TOP 1000 
    u.userid,
    a.afiliacionID
FROM
    pv_usuarios u
CROSS JOIN
    pv_afiliaciones a
ORDER BY
    NEWID(); -- NEWID() para obtener un orden aleatorio y así seleccionar IDs aleatorios


select * from pv_afiliacionesUsuario