-- no requiere tablas extras

INSERT INTO pv_entidadesIA (tipo, texto, confianza, posicionInicial, posicionFin) VALUES
('LEY', 'El Artículo 3 de la Constitución garantiza los derechos fundamentales del ciudadano.', 0.85, 4, 13),
('INSTITUCION_LEGAL', 'La demanda fue presentada ante el Juzgado de Primera Instancia de Madrid.', 0.92, 33, 64),
('PARTE_LEGAL', 'El demandante solicitó una indemnización por los daños y perjuicios sufridos.', 0.78, 4, 16),
('PARTE_LEGAL', 'La defensa del acusado presentó nuevas pruebas al tribunal.', 0.89, 15, 24),
('INSTITUCION_LEGAL', 'El tribunal dictará sentencia en los próximos días hábiles.', 0.95, 4, 13),
('DOCUMENTO_LEGAL', 'Las cláusulas del contrato de arrendamiento establecen las obligaciones de ambas partes.', 0.81, 19, 44),
('CONCEPTO_LEGAL', 'La resolución debe ajustarse a la legislación vigente en materia de propiedad intelectual.', 0.88, 28, 47),
('CONCEPTO_LEGAL', 'El caso se enmarca dentro del ámbito del derecho civil, específicamente en contratos.', 0.93, 30, 42),
('CONCEPTO_LEGAL', 'La decisión se basó en la jurisprudencia reciente sobre casos similares de negligencia.', 0.76, 26, 38),
('LEY', 'El Código Penal establece las sanciones para los delitos contra el patrimonio.', 0.84, 4, 15),
('TERMINO_LEGAL', 'Se considera un acto jurídico válido toda manifestación de voluntad que produce efectos de derecho.', 0.87, 15, 27),
('PARTE_LEGAL', 'Las partes acordaron someter la disputa a arbitraje internacional.', 0.91, 4, 11),
('DOCUMENTO_LEGAL', 'Se requirió un poder notarial para la representación legal en el extranjero.', 0.79, 13, 28),
('CONTRATO', 'Este acuerdo contiene una cláusula de confidencialidad que prohíbe la divulgación de información sensible.', 0.94, 27, 56),
('REGULACION', 'El Real Decreto 123/2023 modifica la normativa sobre protección de datos personales.', 0.86, 4, 26),
('INSTITUCION_LEGAL', 'La investigación fue remitida a la Audiencia Nacional por su complejidad.', 0.90, 31, 48),
('PARTE_LEGAL', 'El heredero legítimo ha aceptado la sucesión sin reservas.', 0.75, 4, 14),
('DOCUMENTO_LEGAL', 'El testamento fue redactado en presencia de tres testigos cualificados.', 0.82, 4, 14),
('CONCEPTO_LEGAL', 'La prescripción de delitos graves se interrumpe con la interposición de una querella.', 0.83, 4, 26),
('ROL_LEGAL', 'El fiscal solicitó la pena máxima para el imputado por reincidencia.', 0.96, 4, 12),
('PROCEDIMIENTO_LEGAL', 'Se interpuso un recurso de apelación contra la sentencia del juzgado de primera instancia.', 0.77, 15, 34),
('CONCEPTO_LEGAL', 'El trabajador tiene derecho a una indemnización por despido improcedente según la legislación laboral.', 0.91, 28, 56),
('LEY', 'Los plazos procesales se rigen por la Ley de Enjuiciamiento Civil.', 0.88, 30, 57),
('LUGAR_LEGAL', 'La última instancia en este tipo de casos es el Tribunal Supremo.', 0.93, 40, 55),
('PARTE_LEGAL', 'El letrado de la defensa argumentó la inocencia de su cliente.', 0.80, 4, 12),
('CONTRATO', 'El pago de las arras confirmatorias se realizó al firmar el precontrato.', 0.85, 14, 33),
('DOCUMENTO_LEGAL', 'La venta del inmueble se formalizó mediante escritura pública ante notario.', 0.90, 32, 50),
('CONCEPTO_LEGAL', 'La cuantificación de los daños incluyó el daño emergente y el lucro cesante.', 0.79, 30, 43),
('REGULACION', 'La nueva directiva europea obliga a los estados miembros a adaptar sus leyes de consumo.', 0.92, 4, 22),
('INSTITUCION_LEGAL', 'La fiscalía abrió diligencias de investigación preliminares.', 0.84, 4, 13),
('PARTE_LEGAL', 'La declaración de la víctima fue crucial para el desarrollo del juicio.', 0.87, 24, 33),
('PROCEDIMIENTO_LEGAL', 'El juicio oral se celebrará la próxima semana con la presentación de pruebas.', 0.95, 4, 14),
('CONCEPTO_LEGAL', 'Todo ciudadano tiene derecho a la tutela judicial efectiva, sin indefensión.', 0.77, 30, 52),
('LEY', 'Las sociedades mercantiles se constituyen conforme al Código de Comercio.', 0.89, 44, 62),
('TERMINO_LEGAL', 'Se determinó la responsabilidad civil subsidiaria de la empresa.', 0.91, 15, 34),
('DOCUMENTO_LEGAL', 'Se ha presentado una demanda ejecutiva para el cobro de la deuda.', 0.81, 24, 42),
('ROL_LEGAL', 'El perito presentó su informe técnico ante la corte.', 0.86, 4, 11),
('CONCEPTO_LEGAL', 'La extinción de la pena se produce por cumplimiento o por indulto.', 0.90, 4, 21),
('INSTITUCION_LEGAL', 'Se solicitó una nota simple en el Registro de la Propiedad para verificar la titularidad.', 0.78, 29, 52),
('CONTRATO', 'El incumplimiento contractual puede dar lugar a la rescisión del acuerdo.', 0.93, 4, 28),
('LEY', 'La Ley Orgánica 1/2015 endurece las penas por determinados delitos económicos.', 0.85, 4, 25),
('PROCEDIMIENTO_LEGAL', 'El auto judicial ordenó el embargo de los bienes del deudor.', 0.92, 4, 17),
('TERMINO_LEGAL', 'La resolución adquirió firmeza y tiene valor de cosa juzgada.', 0.80, 42, 54),
('LUGAR_LEGAL', 'El caso fue remitido a la Sala de lo Contencioso-Administrativo.', 0.88, 28, 64),
('CONCEPTO_LEGAL', 'La reincidencia es un agravante en el cálculo de la pena.', 0.94, 4, 16),
('DOCUMENTO_LEGAL', 'El convenio regulador estableció las medidas relativas a la custodia de los hijos.', 0.76, 4, 23),
('ROL_LEGAL', 'El notario certificó la autenticidad de las firmas en el documento.', 0.87, 4, 12),
('LEY', 'El Reglamento General de Protección de Datos (RGPD) entró en vigor en 2018.', 0.91, 4, 48),
('DOCUMENTO_LEGAL', 'La sentencia es firme y ha adquirido carácter de cosa juzgada.', 0.89, 4, 13),
('PARTE_LEGAL', 'Ambas partes firmaron el acuerdo transaccional sin objeciones.', 0.82, 6, 17),
('CONCEPTO_LEGAL', 'La nulidad de pleno derecho fue declarada por el juez.', 0.93, 4, 25);