INSERT INTO pv_criteriosExito ([titulo], [descripcion]) VALUES
('Asistencia Eventos >80%', 'Alcanzar una asistencia del 80% o más en los eventos comunitarios planificados por el proyecto.'),
('Reducción Burocracia 20%', 'Reducir los tiempos de espera en trámites públicos relacionados con el proyecto en un 20% mediante optimización de procesos.'),
('Aumento Reciclaje 15%', 'Incrementar la tasa de reciclaje en la comunidad objetivo en un 15% medida trimestralmente.'),
('Nuevas Empresas Locales +10', 'Fomentar la creación de al menos 10 nuevas microempresas o emprendimientos locales al finalizar el proyecto.'),
('Mejora Calidad Aire 10%', 'Demostrar una mejora del 10% en la calidad del aire local, verificada por datos de monitoreo ambiental.'),
('Capacitación Completada 95%', 'Lograr que el 95% de los participantes inscritos completen los programas de capacitación ofrecidos.'),
('Acceso Agua Potable 98%', 'Ampliar el acceso a agua potable segura al 98% de los hogares en la zona de intervención.'),
('Reducción Accidentes 5%', 'Disminuir el número de accidentes o incidentes críticos en áreas públicas en un 5% anualmente.'),
('Uso Espacios Públicos +30%', 'Incrementar el uso de los espacios públicos revitalizados en un 30% medido por conteo de usuarios.'),
('Satisfacción Servicios 88%', 'Alcanzar un 88% de satisfacción con los nuevos servicios públicos implementados, según encuestas.'),
('Conciencia Salud +20%', 'Aumentar el nivel de conocimiento sobre prácticas de salud preventivas en un 20% en la población objetivo.'),
('Particip. Volunt. +50%', 'Incrementar la participación en actividades de voluntariado comunitario en un 50% en el año del proyecto.'),
('Proyectos Vecinales +5', 'Impulsar al menos 5 proyectos vecinales autogestionados y sostenibles con apoyo del programa.'),
('Reducción Morbilidad 3%', 'Reducir la morbilidad de una enfermedad específica en un 3% en el grupo demográfico objetivo.'),
('Acceso Digital 75%', 'Garantizar el acceso a herramientas digitales para al menos el 75% de los adultos mayores de la comunidad.'),
('Viviendas Rehabilitadas 50', 'Rehabilitar y mejorar las condiciones de al menos 50 viviendas en áreas prioritarias.'),
('Generación Empleo Local 15%', 'Aumentar la generación de empleo local en un 15% para los beneficiarios del proyecto.'),
('Índice Seguridad +15%', 'Mejorar el índice de percepción de seguridad ciudadana en un 15% en la comunidad intervenida.'),
('Aumento Oferta Cultural 40%', 'Incrementar la oferta de actividades culturales y recreativas en un 40% en el área de influencia.'),
('Cumplimiento Plazos 90%', 'El 90% de las fases clave del proyecto se completarán dentro de los plazos establecidos, verificable por cronograma.');
